Repository LilyAcorn/django-rusty-templates, pull requests merged in 2024-12, with the labels that each got.

#32 Add tests for CachedLoader
  src/loaders.rs
Labels: testing

#33 Stop using CODECOV_TOKEN
  .github/workflows/python.yml
  .github/workflows/rust.yml
Labels: ci

#34 Cache the LoaderError in CachedLoader
  src/loaders.rs
Labels: bug

#35 Update build.yml with latest maturin
  .github/workflows/build.yml
Labels: ci

#36 Add locmem loader implementation with tests
  src/loaders.rs
Labels: enhancement

#38 Add `default` and `lower` filters
  src/parse.rs
  src/render.rs
  src/template.rs
Labels: enhancement

#39 Try getting rust coverage from python tests
  .github/workflows/python.yml
Labels: ci

#41 Start implementing tags
  src/lex.rs
  src/lex/common.rs
  src/lex/tag.rs
  src/lex/url.rs
  src/lex/variable.rs
  src/lib.rs
  src/parse.rs
  src/render.rs
  src/template.rs
  src/utils.rs
  tests/settings.py
  tests/tags/test_url.py
  tests/test_django.py
  tests/urls.py
  tests/views.py
Labels: enhancement

#42 Tidy the current_app helper function
  src/render.rs
Labels: refactor
